* 人
** 人的本质
*** 物质性
1.人的本质是人自身;
2.人的本质是人的需要;
3.人的本质是自由的有意识的劳动
*** 社会性
人的本质不是单个人所固有的抽象物，在其现实性上，它是一切社会关系的总和
*** 人与需求
“需求”和“满足需求”，不是在满足自己的需求的路上，就是在满足别人的需求的路上
*** 人与业务
1.首先，业务是服务提供方满足需求方诉求的主要形式;
2,其次，业务是服务提供方和需求方共同构成的对立统一体;
3.最后，人的本质决定了业务的存在与否;

* 业务
** 定义
定义：一些人通过有组织的劳动，满足另外一些人的需求，从而获取回报，并能够持续运转下去的整个过程，可以统称为业务。
** 客户
定义：个人或一类人，以市场的形态出现
角色：需求方，消费者
核心利益诉求：以尽可能低的价值付出，得到需求的满足；或者以合适的价值付出，得到高水平的需求满足。
** 企业
定义：个人或一群人，常以组织的形态出现
角色：服务提供方，生产者
核心利益诉求：将自己的劳动结果尽可能多的换取想要的价值，这一过程尽可能长久
** 价值载体
定义：满足需求方需求的事物，常以广义的商品的形态出现
角色：广义的商品（包含物质的商品，也包含虚拟的服务等）
核心利益诉求：价格体现价值

* 商业
** 本质
交易，货币切分了买卖，商人连接了交易。商业的本质，是交易。更先进的商业，就是更高效的交易。
** 克服阻力：交易成本
信息不对称/信用不传递
*** 购前
1. 搜寻成本(淘宝)
2. 比较成本(比价/大众点评)
3. 测试成本(品牌溢价/SGS)
*** 购中
1. 协商成本(IM)
2. 付款成本(支付宝)
*** 购后
1. 物流成本(菜鸟)
2. 售后成本(京东)

** 交易目的
多快好省
*** 多
商品多，品类齐全
*** 快
效率，物流
*** 好
体验，决策链
*** 省
营销，价格

** 零售场景：人货场
把商品给用户进行价值交换，“场”连接着“人”与“货”
*** 人
不论对电商还是实体商家，不论叫消费者，用户，客户，其本质都是流量。
没有流量，货和场都失去意义，最早在百度的做得竞价广告，淘宝的商户有付费直通车，后来拼多多有做特价活动，
还有在微信的私域流量，还有正火的短视频里定向投放，这些越来越精细化的操作，本质都是一件事：找人，获得流量
*** 货
这里要引入微笑曲线，概括了一个物品从生产到变成商品的全过程
拆解下来就是： D→M→S→B→b→C
以耐克为例
D (Design设计）：在新罕布什尔州埃克赛特镇设置的运动研究实验室
M（Manufacture制造商/工厂）：中国，越南，印度尼西亚等代工厂
S（Supply Chain供应链/供应商）：百丽和宝胜国际等提供订货会
B（Business大B是商场/超市/大卖场等）：博韬体育这类综合性运动用品商店
b（business小b，商店，微商，个体户）：虎扑，咸鱼上的黄牛
C（Consumer消费者/终端客户）：最终买了自己穿或者收藏的消费者
*** 场
具象来说是我们发生交易的一切场所，商店，超市，商场，餐厅，网店....
概括来说是实现消费者获取与商品价值转化的地方。即商品惊险一跳的发生地。
那么它由什么组成呢？信息流、资金流、物流



