* CRM 概念
定义:custom relationship management
企业利用相应的信息技术以及互联网技术来协调企业与顾客间在销售、营销和服务上的交互，
从而提升其管理方式，向客户提供创新式的个性化的客户交互和服务的过程。
其最终目标是吸引新客户、保留旧客户以及将已有客户转为忠实客户。


**  发展历史
萌芽时期（1980）：CRM开始萌芽，企业决策者开始关注销售自动化（SFA）、客户服务系统（CSS），结合起来就是今天CRM的前身
正式诞生（1999）：Gartner Group公司正式提出了CRM概念（Customer Relationship Management 客户关系管理），CRM概念正式出现在大众视野
国内落地（2000）：国内CRM市场开始启动，市场区域主要集中在北京上海等经济发达地区，但国外的CRM理论在国内显得有些“水土不服”
百花齐放（2010）：至今，国内CRM市场百花齐放，出现了各种形式的CRM软件，其中包括：通用型CRM软件、行业垂直类CRM软件、社交类CRM软件、灵活搭建类CRM软件等

** 定义
提起销售信息化，大部分人第一反应就是CRM。所谓CRM，即Customer Relationship Management（客户关系管理），其概念自萌芽到如今的百花齐放，也经历了几十年的时间：
在这几十年中，CRM作为信息化领域的热门概念，自诞生来被多次定义：
*** Gartner Group
CRM是一种商业策略，它按照客户的分类情况有效地组织企业资源，培养以客户为中心的经营行为以及实施以客户为中心的业务流程，并以此为手段来提高企业的赢利能力、利润以及客户满意度。此定义明确指出了CRM并非某种单纯的IT技术，而是企业的一种商业策略，注重企业赢利能力和客户满意度。
*** Hurwitz Group
CRM的焦点是改善与客户关系有关的商业流程(如销售、市场营销、客户服务与支持等)，并使之实现自动化。CRM既是一套制度原则，也是一套软件和技术，目的是缩减销售周期和销售成本，增加收入，寻找新的市场和渠道，旨在提高客户的价值、满意度、赢利性和忠诚度。
*** IBM
CRM通过提高产品的性能，增强客户服务，提高客户交付价值和客户满意度，与客户建立长期、稳定、相互信任的密切关系，从而为企业吸引新客户、维系老客户的“完整生命周期”；对企业来说，CRM涉及企业前台和后台，需要整个企业信息集成和功能配合；对于具体操作来说，CRM体现在企业与客户的每次互动上，这些互动都可能加强或削弱客户参与交易的愿望。
*** Oallup
策略+管理+IT。策略是指战略，管理指战术，IT指工具。这是个简单的公式，却蕴藏着复杂的定义。三个方面缺一不可。
*** 中国客户关系管理研究中心
CRM是先进的管理与信息科技结合的典范，是企业为提高核心竞争力，重新树立以客户为中心的发展战略，并在此基础上开展的包括判断、选择、争取、发展和保持客户所需实施的全部商业过程；是企业以客户关系为重点，通过开展系统化的客户研究，优化企业组织体系和业务流程，提高客户满意度和忠诚度，提高企业效率和利润水平的完整管理实践，也是企业不断改进与客户关系相关的全部业务流程，努力实现电子化、自动化运营过程中，所创造和使用IT技术、软硬件及优化方法、集成方案等的总和。
*** 维基百科
客户关系管理是一种企业与现有客户及潜在客户之间关系互动的管理系统。通过对客户数据的历史积累和分析，CRM可以增进企业与客户之间的关系，从而最大化增加企业销售收入和提高客户留存。
*** 百度百科
客户关系管理是指企业为提高核心竞争力，利用相应的信息技术以及互联网技术协调企业与顾客间在销售、营销和服务上的交互，从而提升其管理方式，向客户提供创新式的个性化的客户交互和服务的过程。其最终目标是吸引新客户、保留老客户以及将已有客户转为忠实客户，增加市场。

以上不管哪个维度的定义，其本质都大同小异，这里我们可以选择便于理解的维度去参考。总之，对CRM概念理解上需要梳理清楚几个关键点：

CRM主要用于管理销售前中后环节，目的多是提升销售业绩；
CRM不仅是一套信息化工具，更是一种销售管理、客户管理思维的体现。

** CRM价值
在这个信息化技术高速发展的时代，作为企业业务核心的销售团队，一旦成功实现信息化，对企业带来的价值都是难以估量的。

一般来说，CRM给企业增加价值主要从几方面来体现：

提升客户满意度：整合客户信息并共享给公司内部员工，用客户喜欢的方式为客户服务，帮助员工为客户提供更周到的服务
降低企业成本：用科学的方式重新设计企业业务流程，更有效地进行客户管理，降低企业成本
提升员工效率：通过信息技术（各类CRM软件的落地），提高业务处理流程的自动化程度，进一步提升员工的工作效率
辅助科学决策：CRM软件帮助企业获取更丰富的数据、更智能的分析，这些都将成为企业进行决策和经营活动的依据




* 个人怎么理解CRM
** 概念分类
概念:企业/客户连接价值
企业(销售、客服、运营)商品提供方；客户，商品消费方；
关系管理(连接产生价值:建立、激活、维持、加深、重连)
** 按照提供方分类(销售/客服/会员营销)
销售 SFA
挖掘潜在客户（Lead），将这些潜在客户转换为正式的客户（Account），并维护好客户的相关联系人
(一个企业客户通常会有多种角色的联系人)，结合企业自身的产品/服务，这些客户会拥有若干的业务机会
（Opportunity），跟进过程中，客户的问题，被作为个案（Case）沉淀记录下来。
客服 CRM工具service
营销 Marketing/Growth
** 按照消费方分类(2B/2C)
● 2B的CRM会跟注重线索和关键联系人，通常注重电话与拜访，比较倾向于SFA(销售能力自动化)；
● 2C的CRM会更注重用户喜好与定向服务，通常通过线上的数据化运营或者企业微信/社群运维。

** 按照行业分类

* CRM和ERP、SCM、OA

* CRM技术类需求
** 围绕人(客户)的数据聚合能力
1. 数据归一和人群服务
人群实现方式：id集合/会员标签
2. 人群筛选和计算
3. 用户画像(tag)

** 流程和自动化
1. 异构数据的输入
2. 内部流程编排
3. 规范数据的输出

** 运营诊断和分析
1.

** 智能触达和运营
1. 工作流
2. 权限控制
3. 智能决策
4. 策略实验

* 竞品Salesforce










