* 营销
菲利普·科特勒《营销管理》


* 演进

** 单一观念
生产观念，它认为，消费者更喜欢便宜且哪里都买得到的产品，因此Marketing更多体现为大规模分销。这种观念在商品流通不发达的时代表现最为明显，例如1990年以前的中国。
产品观念，它认为，好的产品就能自己吸引消费者购买，Marketing更多体现为竞品研究。这会导致许多新奇、无用、没市场的产品出现或者是企业对技术指标的一味追求，这种观念在创新创业热情高涨的时代表现最为明显，例如中国2012年前后。
推销观念，它认为，顾客在没有外力推动下不会购买，因此Marketing体现为硬性推销。这种观念在产能过剩的市场体现最为明显，许多持“产品观念”的企业在后期也会转变为“推销观念”，试图说服消费者购买他们不需要的东西。

** 营销组合观念(4P+STP+CRM)
STP企业通过消费者洞察与市场调查，了解消费者有哪几类（S市场细分），自己最有优势的是哪类消费者（T目标市场选择），
自己要在这类消费者大脑中占据“最”什么或“第一”什么的位置（P定位）。
4P完成STP之后，企业以独占目标消费者大脑中的目标位置为出发点与目标为消费者制造产品价值与塑造品牌价值（4P之产品与价格）、
提供产品与品牌价值（4P之渠道）、传播产品价值与品牌价值（4P之宣传，特别说明国内多数市场营销教科书将4P中的“Promotion”翻译为“促销”与“销售促进”都是极其脑残的，
因为促销本身是Promotion中的一个组成部分，而销售促进则不包含传播品牌价值，都是云遮雾绕的译法）。
CRM做好上述价值创造工作，我们就可以通过客户关系管理（CRM）与内外部消费者建立并维持关系，并持续获得产品利润与品牌利润的回报了。

** 全方位营销观念
一方面，它是一种思维，无处不在；另一方面，从企业职能来看，也意味着Marketing成为核心战略，将客户价值与公司运营合一，
正如菲利普·科特勒为我们上一本书作的序言中写到的：营销作为公司价值创造的中枢，要上升称为一种CEO的市场战略。
——也就是我所主张的Marketing as Strategy.

** 营销全景
1. “流通说”:营销是让大生产有效对接大消费的工具1960年美国市场营销协会提出：“营销是引导货物和劳务从生产者流向消费者或用户所进行的一切业务活动“，
于是营销成为产业社会打通流通领域，使得大生产有效对接大消费的工具。流通是价值链层面的宏观视野，它让我们能够理解这样一句话，营销是帮助经济学落地的工具。
而事实上，菲利普·科特勒本人即是经济学背景，他的弟弟、全球实战派营销大师、科特勒咨询全球总裁米尔顿·科特勒，也是师从大名鼎鼎的自由主义经济学家哈耶克。
需要指出的是，流通说强调三大领域——生产、流通、消费的贯穿，不只是渠道铺货等流通工作。它的弱点在于：缺乏细节。
2. “需求管理说”：营销是有利可图地满足需求科特勒咨询（中国区）合伙人王赛曾当面让菲利普·科特勒用一个词精准定义营销，
菲利普给出的答案就是“需求管理”。《营销管理》中也说，关于营销最简洁的定义是，“有利可图地满足需求”。
需求管理说主张“识别尚未满足的需要和欲望，估量和确定需要量的大小，选择和决定企业能最好的为它服务的目标市场，
并且决定适当的产品、劳务和计划，以便为目标市场服务”。需求管理说从根本上抓住了企业利润的来源点，整个策略体系构建也最为完整，
占据营销学说的绝对地位，受到大家广泛认可，但其弱点也较为明显：过于关注购买前的营销活动，而忽视购买后的营销活动；同时也没有充分地考虑到竞争。
3. “竞争说”：营销是算计、包围并战胜竞争对手杰克·特劳特是竞争说的代表。他认为“市场营销的本质不是为客户服务，
而是算计、包围并战胜竞争对手”。持这种看法的企业家也不在少数，因此中国商人爱读《孙子兵法》、外国商人爱读克劳塞维茨的《战争论》。
特劳特和他的合作者里斯也将军事思想引入市场营销中，出版了作品《商战》（Marketing Warfare ）。竞争说的弱点在于：以竞争为核心的营销极易导致所有企业进入同一市场，
陷入红海，局限了对新兴市场的开拓。
4. “差异说”：营销是跟竞争对手不一样差异说是竞争说的演进，即差异化能够创造竞争优势。差异说认为，营销就是创造差异，
和竞争对手进行有效区隔。许多学者在这个领域提出过自己的观点，比如竞争战略之父波特、《紫牛》作者塞斯高汀（Seth Godin）等。
王赛博士本人也提出了一个有趣的观点：生态位营销。生态位是恰好被一个物种或亚物种所占据的最后分布单位，生物要想生存，
就要向差异的方向进化，占领不同的生态位。企业的营销策略亦有相似性。
5. “垄断说”：营销是为了达到垄断垄断说是竞争说的另一种演进，即企业的营销策略就是要试图达到或者接近垄断效果，
才能获得最大利润。微观经济学认为，市场结构有四类：完全竞争市场、垄断竞争市场、寡头市场和垄断市场。
垄断说认为，市场细分的目的是切割出自己可以垄断的市场，定位的目的是垄断消费者的心智资源……垄断是所有营销活动的核心目的。
6. “价值设计说”：营销是比竞争对手更好地提供客户价值价值设计说认为，营销的本质就是比竞争对手更好地提供客户价值。
价值设计说回避了单一地去讨论需求这个概念，综合竞争者提供的价值来综合考虑。价值设计说的代表是《蓝海战略》，作者W·钱·金（W. Chan Kim）
和勒妮·莫博涅（Renee Mauborgne）——两位INSEAD商学院教授最初在《哈佛商业评论》上发表此观点时，将其称为“价值创新策略”。
7. “关系管理说”：营销是建立和维护与客户的长期关系20世纪70年代开始，斯堪的纳维亚半岛和北欧的学者提出了以建立和管理“关系”为基础的营销，
试图替代传统营销观念的架构。他们认为，营销应是在获利的基础上，通过建立、维持和促进与客户长期的关系，以便满足参与交易各方的目标。
现实商业中，许多CMO的实际工作大多是交易后的客户管理工作，尤其是B2B类的企业。而随着互联网的兴起，B2C企业同样也开始注重管理好与消费者的“关系”，
形成相互嵌入的关系型社区。应该说，相对于构建暂时性的、战术优势的“需求管理”，“关系管理”意图在搭建一个长远的、战略性的、共生的“消费者-企业”生态，这的确是一个认知上的飞跃。
8. “客户资产管理说”：营销是管理企业所有客户的终身价值客户资产管理说是关系管理说的演进与发展，从营销学百年的变迁来看，
营销学发展的主线就是从“产品导向”走向“客户导向”，这是毋庸置疑的趋势。客户资产就是企业所有客户终生价值折现值的总和。
看到这里，我们就能明白，为什么互联网公司可以将用户作为融资的谈判筹码和估值依据，根源在于此。通过建立客户资产，
企业能够获得面向未来的竞争优势，这是对营销的再一次升级。
9. “交易成本说”：营销是为了降低交易成本商业始于交换，交易成本说认为，无摩擦交换不会产生营销，
营销的目标是消除和降低交换所产生的成本。因此，交易成本是营销存在基础。
10. 营销“信息不对称说”：营销是为了在信息不对称的市场发射信号1970年，乔治·阿克洛夫发表了《柠檬市场：质量不确定和市场机制》，
描述了商品市场中信息不对称的现象及其后果，并以此摘取了2001年的诺贝尔经济学奖。
他为了我们揭示了一个被忽略的事实：在商业活动中，交易双方对于他们面临选择的商品或服务拥有的信息并不完全相同。
而正是因为信息不对称，才有营销存在，因此，信息不对称也是营销存在的基础之一。

** 汇总
最后，我们再看综合回顾这十大流派：
信息不对称和交易成本是营销存在的基础
需求管理是营销的核心，它更关注交易发生前的活动
流通说和竞争说是对需求管理的侧面补充
竞争说存在三个分支流派：垄断、差异、价值设计
交易发生后，营销重心转向关系管理和客户资产管理

* 营销思维
营销就是A为B创造对方想要的价值，建立与维持关系，以获得回报的思维过程。
STP+4P+CRM

** 员工成长
把“员工”代入A，把“老板”代入B，我们可以得到这样一个定义：职业生涯就是员工为老板创造对方想要的价值，建立与维持关系，
以获得回报的过程。过程表达式：知道老板有哪几类，自己最适合的老板的是哪类，自己要成为该类老板心中什么岗位不可或缺的人才；
通过努力使自己符合该类老板心中该岗位不可或缺的人才的标准，为公司持续贡献价值，并让老板耳闻目染你的价值与贡献；
建立并维持相互忠诚的雇佣关系，老板离不开你之后就可以获得提薪或升职了。
