* 通用概念

** 事物
事物，是指不以人意志为转移的存在事情和物体。
*** 事
意志的行为是为事。在人类世界，本身不存在、只因人的存在而存在、可以用时间概念来描述的一切就是事。人们对事的描述加深了人们对物的认识。
事是意志的描述。世界无意志，世界本无事，自然无意志，自然也无事，人有了意志就有了事。事是伴随着人的产生而产生的，世界没有人，也就没有了事，人没有了意志，事也就没有了原因，人们把与人的行为有关的一切称之为事，事因人的存在而存在，在人类社会才有，一切的事皆离不开人的因素。事本身无谓大小无谓轻重，一切大小轻重之事的情形皆因人本身的思想意识而异。
*** 物
存在的一切是为物。自然环境里，不因人的存在而存在的本身通过认识能用空间概念来描述的一切就是物。物的存在是一切有无和存在包括人出现的基础。
物是认识的存在。宇宙的变化，来自于物的存在，没有物的作用影响，变化无所显现，没有物的存在，也不存在有无，没有物的世界，也不能用无来概括，没有物无就不会有出处。物变化的现象让人认识到了物存在的本质，物的本质使人们有了进一步对事的描述。存在的物本身无优劣好坏之分，物的存在是相对于物的变化而言的，人们对变化现象里认识的存在称其为物，正是物的变化加深了人们对物的认识。事的描述促进了人们对时间概念的感知，物的变化促进了人们对空间概念的感知，变化着的物体现了物本身的各种特性，人根据物的各种特性分门别类的给物定义了各科名目。
物有变化，物呈现的变化是现象，现象因物变化的存在而发生，存在的现象因人的描述而成其为事，人对事的认同接受而成为实，从而有了事实。物的本身只是人认识的存在根据人自身的文化方式给各自取了名目。

** 人
人的本质是物质性和社会性，物质性
*** 物质性
1.人的本质是人自身;
2.人的本质是人的需要;
3.人的本质是自由的有意识的劳动

** 概念
是人类在认识过程中，从感性认识上升到理性认识，把所感知的事物的共同本质特点抽象出来，
加以概括，是自我认知意识的一种表达，形成概念式思维惯性。在人类所认知的思维体系中最基本的构筑单位。

** 定义
对于一种事物的本质特征或一个概念的内涵和外延的确切而简要的说明
** 目标
指的是射击、攻击或寻求的对象，也指想要达到的境地或标准

** 需求
概念：直接或间接满足人类生理和心理
详细：生理(衣食住行工作娱乐社交)心理(安全精神)

** 产品
定义：产品是指被人们使用和消费，并能满足人们某种需求的任何东西，包括有形的物品、无形的服务、组织、观念或它们的组合

** 运营
定义：运营是为产品而服务的，是通过有限的资源，利用运营手段来实现产品价值的最大化。
运营是实现产品的非自然增长

** 平台

* 结构
组成整体的各部分的搭配和安排；
在建筑行业中，指由若干构件，即组成结构的单元如梁、板、柱等，连接而构成的能承受作用（或称荷载）的平面或空间体系。
* 流程
流程就是过程节点及执行方式有序组成的过程。
* 度量
用以计量物品的一些物理属性。
