* 中级
** 项目管理
给自己的开发工作或者项目内容制定细分的的开发计划并控制进度
给自己的开发工作内容制定细分的的开发计划；制定项目中开发计划，控制整个开发的进度；在项目中，协调与其他技术部门在开发上的接口，确定方案
** 开发语言技能
对开发技术产品和解决技术问题所需要掌握的开发语言能力；
1. 能独立解决问题，能够负责重要业务模块的需求分析及设计实现，且对线上部署环境比较熟悉，能够独立分析和快速排查线上故障。
2. 熟悉Java虚拟机原理,Java高级特性和类库，Java网络与服务器编程，Java多线程编程，常见开源产品
3. 具备模块或子系统的架构设计能力,掌握常见的架构设计方法和模式，理解大型网站所需要用到的架构和技术
4. 对于移动开发 熟练掌握Andriod、IOS开发相关知识 移动终端技术 至少在某一方比较精通
5.对于前端开发，独立完成复杂页面前端设计和开发，能够制定前端开发规范。
6.具备辅导他人的能力和技能，有良好的分享习惯
** 架构设计
根据业务和产品目标，具备分层的应用框架设计思想，分布式系统原理，大容量数据存储和检索系统设计能力等
了解分层的应用框架设计思想：SOA，事件驱动等；分布式系统原理：CAP，最终一致性，幂等操作等；大型网络应用结构：消息中间件，缓存，负载均衡，集群技术，数据同步；高可用，可容灾分布式系统设计能力；大容量数据存储和检索系统设计能力：数据库分区，NoSQL，搜索引擎等
** 业务理解
了解公司相关业务及其业务规则，并可能深入理解加以运用
1.对业务产品具有独立沟通、完善业务需求，并识别方案的风险的能力
2.能够在负责的业务上有独立的见解，能提出合理的建议
3.对所支持的业务产品具有独立观点，能很好地解决业务问题
** 运维能力
掌握应用发布和运维，线上故障分析和排查的能力
熟悉应用发布和运维，线上故障分析和排查
** 学习能力
保持学习的心态和成长的愿望，在工作中不断学习和掌握所需新知识和新技能
1.在实现业务需求上，具有持续优化、追求卓越的激情和能力
2.能持续的关注和学习相关领域的知识，并能使用到工作当中
3.能够有意识的培养和辅导团队中的其他同事，为低层级的同事制订成长计划，并辅导执行
** 影响
能够通过沟通、说服等方式对他人的行为、想法造成影响，获取支持，最终使事物的行进方向朝自己的愿望预期发展
能影响项目组或产品线的成员，是项目组或产品线公认的核心人员
部门内
** 目标导向
根据业务目标，能通过行动，克服各种障碍达到工作结果
1.能主动考虑结果导向，能够在拿结果中发挥主要作用
2.理解执行结果达成的关键环节
3.能较好的处理风险
* 高级
** 项目管理
给自己的开发工作或者项目内容制定细分的的开发计划并控制进度
制定项目中开发计划，控制整个开发的进度；在项目中，协调与其他技术部门在开发上的接口，确定方案
** 开发语言技能
对开发技术产品和解决技术问题所需要掌握的开发语言能力；
1. 能独立带领产品或业务向前发展，独立承担架构规划，建设以及调优。
2. 某一领域比较精通，具有一定权威（比如服务化、分布式系统、大型网站架构、大数据量存储、业务分析和规划、中间件等）
3. 在服务化，分布式系统，大型网站架构，大数据量存储，业务分析和规划等某一方面的比较精通。
4. 能够负责复杂度高，平台级产品或跨团队的产品的架构，系统设计和实现。
5. 对于移动开发 全面掌握Andriod开发或IOS开发、部署相关知识 移动终端技术 在多个方面比较精通
6.对于前端开发，能带领设计并实现前端开发框架，带领设计并实现前端开发工具
7.多业务模块设计开发，复杂技术与架构设计，不同业务线关联技术方案的合理设计
** 架构设计
根据业务和产品目标，具备分层的应用框架设计思想，分布式系统原理，大容量数据存储和检索系统设计能力等
熟悉分层的应用框架设计思想：SOA，事件驱动等；分布式系统原理：CAP，最终一致性，幂等操作等；大型网络应用结构：消息中间件，缓存，负载均衡，集群技术，数据同步；高可用，可容灾分布式系统设计能力；大容量数据存储和检索系统设计能力：数据库分区，NoSQL，搜索引擎等
** 业务理解
了解公司相关业务及其业务规则，并可能深入理解加以运用
1.能够对跨产品线的业务进行综合分析。能独立带领产品或业务向前发展，并在产品或业务的规划上具备一定的能力。
2.综合分析能力强，能与不同业务团队沟通协同
3.能够全局的规划和解决产品线的业务问题
** 运维能力
掌握应用发布和运维，线上故障分析和排查的能力
熟悉应用发布和运维，线上故障分析和排查
** 学习能力
保持学习的心态和成长的愿望，在工作中不断学习和掌握所需新知识和新技能
1.能够清晰理解业务线所需技术业务能力，并针对团队制定相应的成长计划，并辅导执行。
2.培养团队的技术氛围，提高团队的综合能力
** 影响
能够通过沟通、说服等方式对他人的行为、想法造成影响，获取支持，最终使事物的行进方向朝自己的愿望预期发展
在所处的业务线具有广泛的影响力，对相应涉及的技术和业务都能有足够的公信力
多部门
** 目标导向
根据业务目标，能通过行动，克服各种障碍达到工作结果
1.结果导向，能够打破常规，坚持为了拿结果做正确的事情
2.推动结果达成，资源与方案推动力
3.能较好的预知、预防风险
* 资深
** 项目管理
给自己的开发工作或者项目内容制定细分的的开发计划并控制进度
** 开发语言技能
对开发技术产品和解决技术问题所需要掌握的开发语言能力；
1. 在P7的基础上，需要在Java开发、Web开发上有多项突出的技能
2.全局技术架构设计规划，复杂问题排查总结,开放的思考，考虑其它上下游业务线的技术架构影响与协同
** 架构设计
根据业务和产品目标，具备分层的应用框架设计思想，分布式系统原理，大容量数据存储和检索系统设计能力等
精通分层的应用框架设计思想：SOA，事件驱动等；分布式系统原理：CAP，最终一致性，幂等操作等；大型网络应用结构：消息中间件，缓存，负载均衡，集群技术，数据同步；高可用，可容灾分布式系统设计能力；大容量数据存储和检索系统设计能力：数据库分区，NoSQL，搜索引擎等
** 业务理解
了解公司相关业务及其业务规则，并可能深入理解加以运用
1. 能独立带领多种产品或业务向前发展，并在产品或业务的规划上具备一定的能力。
2.了解相关技术及业务领域在业界的发展，并能对其架构提出合理建议
3.能从业务和技术的角度进行全局的规划思考
** 运维能力
掌握应用发布和运维，线上故障分析和排查的能力
精通应用发布和运维，线上故障分析和排查
** 学习能力
保持学习的心态和成长的愿望，在工作中不断学习和掌握所需新知识和新技能
能针对业务规划、技术规划，对团队成员进行业务和技术辅导。
** 影响
能够通过沟通、说服等方式对他人的行为、想法造成影响，获取支持，最终使事物的行进方向朝自己的愿望预期发展
网站或公司层面影响
** 目标导向
根据业务目标，能通过行动，克服各种障碍达到工作结果
1.能够对事情进行规划，并能通过推进规划的实施，达到预期的结果
2.规划预测与推动，有自己主导的产品，并产生价值
