* mac常用快捷键
  command+space 切换输入法
  control+space 快捷打开命令
  option+command+shift+esc 强制杀死当前程序
* mac环境配置
  /etc/profile >> ~/.bash_profile
* homebrew包管理
  mac下的包管理和安装工具,基于ruby编写，下载源码然后./configure && make install，
  同时会包含相关依存库。并自动配置好各种环境变量，而且易于卸载。
** 安装
   ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
   卸载
   ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
** 命令
   brew update
   brew search nginx
   brew install nginx
** 源码

* brew-cask应用程序管理
   依赖homebrew，已经编译好了的应用包 （.dmg/.pkg），仅仅是下载解压，放在统一的目录中（/opt/homebrew-cask/Caskroom），
   省掉了自己去下载、解压、拖拽（安装）等蛋疼步骤，同样，卸载相当容易与干净。
   这个对一般用户来说会比较方便，包含很多在 AppStore 里没有的常用软件。
** 安装
   brew tap phinze/homebrew-cask && brew install brew-cask
** 源码
   https://github.com/caskroom/homebrew-cask
** 使用
   brew cask search qq
   brew cask install qq
* 安装oh-my-zsh
  git clone https://github.com/robbyrussell/oh-my-zsh.git
  cd oh-my-zsh
  sh tools/install.sh
  sudo ln -s /etc/profile /etc/zprofile
* 命令行终端颜色
export CLICOLOR=1
export LSCOLORS=gxfxaxdxcxegedabagaca
* iTerm2命令行终端
  下载地址 http://www.iterm2.com/
* coreutils
  Mac OS X 是基于 FreeBSD 的，所以一些工具 ls, top 等都是 BSD 那一套，ls 不是 GNU ls，所以即使 Terminal/iTerm2 配置了颜色，但是在 Mac 上敲入 ls 命令也不会显示高亮，可以通过安装 coreutils 来解决.
  brew install coreutils
  如果不起作用可能是路径问题
  vim /etc/profiles
GNU_HOME=/usr/local/opt/coreutils/libexec
export PATH="$GNU_HOME/gnubin:$PATH"
export MANPATH="$GNU_HOME/gnuman:$MANPATH"

* emacs
** 基本
   安装
   brew install emacs --cocoa --with-gnutls
   在mac launchpad中显示
   ls -s /usr/local/Cellar/emacs/HEAD/emacs.app /Applications/
* xcode
** 修改键位
   1. 首先找到Xcode中的自带的配置文件
   /Applications/Xcode.app/Contents/Frameworks/IDEKit.framework/Versions/A/Resources/IDETextKeyBindingSet.plist
   2. 然后将下面这段配置添加到文件的最后的这两行之前</dict></plist>
   <key>ECLIPSE Commands</key>
   <dict>
   <key>ECLIPSE Duplicate Current Line</key>
   <string>selectLine:, copy:, moveToEndOfLine:, insertNewline:, paste:, deleteBackward:</string>
   <key>ECLIPSE Delete Current Line</key>
   <string>moveToEndOfLine:, deleteToBeginningOfLine:, deleteBackward:, moveDown:, moveToEndOfLine:</string>
   <key>ECLIPSE Move Current Line Up</key>
   <string>selectLine:, cut:, moveUp:, moveToBeginningOfLine:, insertNewLine:, paste:, moveBackward:</string>
   <key>ECLIPSE Move Current Line Down</key>
   <string>selectLine:, cut:, moveDown:, moveToBeginningOfLine:, insertNewLine:, paste:, moveBackward:</string>
   <key>ECLIPSE Insert Line Above</key>
   <string>moveUp:, moveToEndOfLine:, insertNewline:</string>
   <key>ECLIPSE Insert Line Below</key>
   <string>moveToEndOfLine:, insertNewline:</string>
   </dict>
   3. 重启Xcode，在Xcode菜单中，打开Preferences，选中Key Binding，在右上方搜索GDI
* svn
** 卸载老版本
   1. which svn 查找svn命令所在
   2. ls /usr/bin/svn* 查找所有svn前缀命令
   3. rm -rf /usr/bin/svn* 删除所有svn命令
** 安装新版本
   1. brew options subversion
   2. brew install subversion
   3. svn --version
* 屏幕取色Pochade
