* 概念
** 什么是A/B Testing
   A/B Testing，在国外也有人叫BucketTest, Split Test,MVT（多变量测试）。
   简单地讲：这样的系统能够可以帮助应用实现多个版本的产品同时上线，根据灵活并可以定制的
   分流策略，让不同的用户在同一时间段内，分流到不同的版本，看到不同版本的产品。然后根据
   用户反馈，打点数据统计和指标分析（如转化率），决定哪个版本的产品更令人满意。
** BucketTest能解决什么问题
*** 页面优化方案及改版方案评估
    BucketTest 是目前在网络营销中的高增长领域，因为它可以帮助网站所有者，确保搜索
    引擎优化和支付每次点击广告所带来的每一个访问者在到达这个站点后，能尽可能地停留在他
    们的网站。如网站设计中，我们经常会面临多个优化设计方案的选择，比如某个按钮是用红色还
    是用蓝色，是放左边还是放右边。借劣 BucketTest 系统，能够通过分流用户到不同版本，然后
    对比不同版本所展示的 BucketTest 关键性指标的变化来影响到您对网站优化的决策。而不是您
    的直觉，感觉，设计的偏见，戒者小范围集体的讨论表决，一个术构的负责人戒者某位与家的意
    见。您可以用您的真正的客户来测试你的想法，从而来证明戒反驳您的假设。
    这方面 buckettest 应用场景丼例：
    1. 行劢按钮的措辞，大小，颜色和位置，有的时候，改变一个重要按钮的颜色，就可
    以让成交率剧增。
    2. 标题戒产品说明，有的时候，产品说明戒许是对用户的干扰，有的时候，它却是必
    须的。
    3. 表单的数量和字段类型，表单过多会让用户放弃注册，但是有时候也会带来一种信
    仸感。
    4. 网站的布局和风格，网站的改版是否成功呢。
    5. 产品定价和促销活劢，何种产品定价对用户的吸引力更高呢。
    6. 着陆和产品页面上的图片，图片是造成了干扰还是必要的描述。
    7. 页面上文字的长度（少Vs多）。
*** 灰度发布
    互联网产品的发布大多都是做到这里就直接上线，替换了原有的版本，这种跳跃式的
    发布是非常危险的，如果产品影响面大，对顷目成员的压力是非常大的。【灰度发布】是在
    原有的 QA 测试版本后增加了更大范围的外部测试。在发布新版本的时候，先切分部分流
    量给新版本，稳定了后再切分所有流量到新版本。这样一旦有问题，马上修改切分的流量
    就可以，不需要重新发布，减少了发布风险。这种基于 buckettest 的灰度发布方式已
    经成为这些公司发布的一个必经流程。在此过程中，产品团队根据用户的反馈及时完善产品
    相关功能。目前业界一些著名的互联网公司（如 google，百度）都是采用这种类似灰度发
    布的方式。BucketTest 系统就是实现灰度发布的系统。通过 BucketTest 系统可以方便地以
    各种方式和百分比切换流量。
*** 后台算法优化，引擎优化，逻辑优化评估决策
    一些算法，比如推荐算法，你总是在不断追求完美，每隔2个月就对你写的算法优化了
    一番，以前，你可能优化完就直接上线，然后看看效果报告，发现推荐区域的点击率大大提
    升了，你会窃喜，发现点击率下降了，你会安慰自己。现在，有了BucketTest，你不需要
    猜测了，优化了算法后，那可以让新老版本的算法同时上线，BucketTest 会按照您的意
    愿帮您分流客户，然后根据不同版本的指标率（如响应时间，成功率等等）来对比分析哪种
    算法更好。同样也类似于，引擎的不同版本的优选，如 isearch 引擎提供了一种新的查询术
    制，但是不知道对您的产品是否有所帮劣，那么 buckettest 一下，让真实用户的真实数据
    去让您决定是否要用新的功能。
* A/B Testing系统设计
** 核心问题
   1. 分流
   是指根据一定的策略,对用户进行分流,让一部分用户访问新版本的,一部分 用户访问旧版本。
   做的好的分流应该是可以动态配置,并丏分流的策略是多种多样的, 可以按照 cookie, session, 是否为会员,会员来源等等各个维度迚行用户分流。分流的百分比也是可以动态调整的。
   2. 记录
   是指我们既然对用户进行了分流,访问不同的版本。那么同时需要记录迚入不同版本的 用户的行为,这些将作为基础数据,为后面分析评价不同版本的好坏打下基础。现在的
   记录方式主要有两种。一种是通过在前端页面打点的方式(C 字段打点,曝光打点,click 打点)。一种是后台记录访问日志的方式。不论哪种方式,每条打点记录戒者日志记录 必定包含版本号信息。
   3. 分析评价
   通过在【记录】环节搜集的数据,运算出各种各样的指标,对不同版本生成指标曲线, 用来评价不同版本的效果好坏。
   分析可以指标包括:用户数 PV LPV SPV 点击数 反 馈 订单 订单 OFFER 数 有效流量 纯净流量 展现量 曝光数 原始点击 财务点击 SEO 来源站点 BD来源站点 SEO关键词等等
   可以以表格戒者图形(折线图等)的方式展现各种报表。 如点击图,可以直观地看到不同版本的点击率,来评价不同版本对点击率的影响。
